"""Embed the exact checkout identity before PyInstaller packages the app."""
from pathlib import Path
import sys

repository = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(repository))
from app_version import identity

info = identity()
if not info.get('commit'):
    raise SystemExit('Cannot package an unidentified build.')
(repository / 'build_info_generated.py').write_text(
    '# Generated by scripts/write_build_info.py; do not edit.\nBUILD_INFO = ' + repr(info) + '\n',
    encoding='utf-8')
print('Embedded build identity:', info)
